### PR TITLE
Add linux fox

### PR DESCRIPTION
**Pull request by x44203**

### CODE REVIEW

**Review by e1mo — CHANGES_REQUESTED** [review]
While I like the fox, I am in strong opposite of renaming emojis in general and especially at that scale. If you rename emojis it will break old posts where those were used I think.

**Comment by x44203** [comment]
How can I do that? I had an old version and did git pull, hoping that it would get to the newest version but apparently now there are renaming issues...

**Comment by x44203** [comment]
That didn't really work, I just deleted my fork and re-forked it.

**Comment by x44203** [comment]
t

**Pull request closed without merging**
